name: Docker Image CI

on:
  push:
    branches:    
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Packages
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_BUILDER }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_BUILDER_TOKEN }}
    - name: NodeJS 8.17.0
      run: make NODE_VERSION=8.17.0 ci
    - name: NodeJS 10.18.0
      run: make NODE_VERSION=10.18.0 ci
    - name: NodeJS 11.15.0
      run: make NODE_VERSION=11.15.0 ci
    - name: NodeJS 12.13.1
      run: make NODE_VERSION=12.13.1 ci
    - name: NodeJS 13.5.0
      run: make NODE_VERSION=13.5.0 ci
